# Generated by Django 5.2.6 on 2025-12-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumechecker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('skills', models.JSONField()),
                ('total_experience', models.FloatField()),
                ('project_categories', models.JSONField()),
                ('suggestions', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumechecker.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumechecker.resume')),
            ],
            options={
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
